# True color
set -g default-terminal "$TERM"
set -ag terminal-overrides ",$TERM:Tc"

# Asignar r para recargar configuración
unbind r
bind r source-file ~/.tmux.conf

# prefijo
set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g mouse on
set -g escape-time 0
set -g repeat-time 1000
set -g history-limit 10000

# Moverse con atajos de vim
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Opciones de server (si hay problemas, desactivar)
set-option -s focus-events on
set-option -s extended-keys on

# Mover barra de estado
set-option -g status-position bottom

# Iniciar paneles desde 1, no 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Cambiar título de tmux por panel actual
set-option -g set-titles on
set-option -g set-titles-string "#{pane_title}"

# Abrir nuevo panel en el directorio actual
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# ============
#  Apariencia
# ============

set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "

set -g status-style bg=default,fg=blue,bright

set -g window-status-style fg=blue,nobold
set -g window-status-current-style bg=black,fg=blue

set -g status-right "\"#h\" | %b-%d-%y %R "

#set -g pane-border-lines simple
